define([], function() {
  return {
    "PropertyPaneDescription": "Configure the search box behavior, suggestions, and scope selector.",
    "BasicGroupName": "Search Box Settings",
    "SearchGroupName": "Search",
    "SuggestionsGroupName": "Suggestions",
    "ConnectionGroupName": "Connection",
    "ScopeGroupName": "Scope",
    "AdvancedGroupName": "Advanced",
    "QueryGroupName": "Query",
    "NavigationGroupName": "Navigation",
    "SearchPageHeader": "Configure search box input, query, and navigation settings.",
    "SuggestionsPageHeader": "Choose which suggestion sources appear in the dropdown.",
    "ConnectionsPageHeader": "Connect the search box to shared search state and optional scopes.",
    "AdvancedPageHeader": "Advanced search-box features and expert settings.",
    "SearchContextIdFieldLabel": "Search Context ID",
    "SearchContextIdFieldDescription": "Web parts with the same context ID share search state. Leave blank for 'default'.",
    "PlaceholderFieldLabel": "Placeholder text",
    "DebounceMsFieldLabel": "Debounce delay (ms)",
    "SearchBehaviorFieldLabel": "Search trigger",
    "SearchBehaviorOnEnter": "On Enter key",
    "SearchBehaviorOnButton": "On button click",
    "SearchBehaviorBoth": "Both Enter key and button",
    "ResetSearchOnClearLabel": "Reset search state when clear is clicked",
    "QueryInputTransformationLabel": "Query transformation",
    "QueryInputTransformationDescription": "Template applied to the user input before executing the search. Use {searchTerms} as the placeholder.",
    "SearchInNewPageLabel": "Redirect to another page on search",
    "NewPageUrlLabel": "Target page URL",
    "NewPageUrlDescription": "URL of the page to navigate to (e.g., /sites/search/SitePages/Results.aspx). The query will be appended as ?q=...",
    "NewPageUrlRequiredMessage": "Enter the target page URL.",
    "NewPageOpenBehaviorLabel": "Open target page",
    "NewPageOpenBehaviorSameTab": "In the same tab",
    "NewPageOpenBehaviorNewTab": "In a new tab",
    "NewPageParameterLocationLabel": "Send query using",
    "NewPageParameterLocationQueryString": "Query string",
    "NewPageParameterLocationHash": "Hash fragment",
    "NewPageQueryParameterLabel": "Query parameter name",
    "NewPageQueryParameterDescription": "Parameter key to use when redirecting, for example q or query.",
    "EnableScopeSelectorFieldLabel": "Enable scope selector",
    "ScopeInfoLabel": "The search box uses the shared search context from the connected Results web part. Enable the scope selector only when explicit scopes are configured.",
    "EnableSuggestionsFieldLabel": "Enable search suggestions",
    "SuggestionsPerGroupLabel": "Suggestions per source",
    "EnableSharePointSuggestionsLabel": "Show SharePoint suggestions",
    "EnableRecentSuggestionsLabel": "Show recent searches",
    "EnablePopularSuggestionsLabel": "Show popular searches",
    "EnableQuickResultsLabel": "Show quick results",
    "EnablePropertySuggestionsLabel": "Show search property suggestions",
    "EnableQueryBuilderFieldLabel": "Enable visual query builder",
    "EnableKqlModeFieldLabel": "Enable KQL mode toggle",
    "EnableSearchManagerFieldLabel": "Enable saved searches button",
    "ToggleOnText": "On",
    "ToggleOffText": "Off"
  }
});
