define([], function() {
  return {
    "PropertyPaneDescription": "Configure the Search Filters web part",
    "FiltersPageHeader": "Configure the refiners shown to users on the page.",
    "ConnectionsPageHeader": "Configure connections to the Search Results web part on this page.",
    "AdvancedPageHeader": "Configure expert filter behavior and builder options.",
    "FiltersGroupName": "Refiners",
    "BehaviorGroupName": "Behavior",
    "ConnectionsGroupName": "Connections",
    "AdvancedGroupName": "Advanced",
    "BasicGroupName": "Filter Settings",
    "DescriptionFieldLabel": "Description Field",
    "SearchContextIdLabel": "Search Context ID",
    "SearchContextIdDescription": "Links this filter web part to a search results web part that shares the same context ID",
    "FiltersFieldLabel": "Refiners",
    "FiltersPanelHeader": "Configure refiners",
    "FiltersManageBtn": "Manage refiners",
    "FilterPropertyColumn": "Managed property",
    "FilterDisplayNameColumn": "Display name",
    "FilterUrlAliasColumn": "URL alias",
    "FilterTypeColumn": "Type",
    "FilterTypeCheckbox": "Checkbox",
    "FilterTypeDateRange": "Date range",
    "FilterTypeText": "Text query",
    "FilterTypeSlider": "Slider",
    "FilterTypePeople": "People",
    "FilterTypeTaxonomy": "Taxonomy",
    "FilterTypeTagBox": "Tag box",
    "FilterTypeToggle": "Toggle",
    "FilterOperatorColumn": "Operator",
    "FilterMaxValuesColumn": "Max values",
    "FilterShowCountColumn": "Show count",
    "FilterExpandedColumn": "Expanded",
    "FilterSortByColumn": "Sort by",
    "FilterSortByCount": "Count",
    "FilterSortByName": "Alphabetical",
    "FilterSortDirectionColumn": "Sort direction",
    "FilterSortDescending": "Descending",
    "FilterSortAscending": "Ascending",
    "FilterMultiValuesColumn": "Multi-select",
    "ApplyModeLabel": "Apply mode",
    "ApplyModeInstant": "Instant (apply on each selection)",
    "ApplyModeManual": "Manual (apply with button)",
    "OperatorLabel": "Logic between refiners",
    "ShowClearAllLabel": "Show Clear All button",
    "EnableVisualFilterBuilderLabel": "Enable visual filter builder",
    "ToggleOnText": "Yes",
    "ToggleOffText": "No",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});
