define([], function() {
  return {
    "PropertyPaneDescription": "Configure the Search Filters web part",
    "FiltersPageHeader": "Configure the refiners shown to users on the page.",
    "ConnectionsPageHeader": "Configure connections to the Search Results web part on this page.",
    "AdvancedPageHeader": "Configure expert filter behavior and builder options.",
    "FiltersGroupName": "Refiners",
    "BehaviorGroupName": "Behavior",
    "ConnectionsGroupName": "Connections",
    "AdvancedGroupName": "Advanced",
    "BasicGroupName": "Filter Settings",
    "DescriptionFieldLabel": "Description Field",
    "SearchContextIdLabel": "Search Context ID",
    "SearchContextIdDescription": "Links this filter web part to a search results web part that shares the same context ID",
    "FiltersFieldLabel": "Refiners",
    "FiltersPanelHeader": "Configure refiners",
    "FiltersManageBtn": "Manage refiners",
    "FilterPropertyColumn": "Managed property",
    "FilterDisplayNameColumn": "Display name",
    "FilterUrlAliasColumn": "URL alias",
    "FilterTypeColumn": "Type",
    "FilterTypeCheckbox": "Checkbox",
    "FilterTypeDropdown": "Dropdown",
    "FilterTypeDateRange": "Date range",
    "FilterTypeText": "Text query",
    "FilterTypeSlider": "Slider",
    "FilterTypePeople": "People",
    "FilterTypeTaxonomy": "Taxonomy",
    "FilterTypeTagBox": "Tag box",
    "FilterTypeToggle": "Toggle",
    "FilterOperatorColumn": "Operator",
    "FilterMaxValuesColumn": "Max values",
    "FilterShowCountColumn": "Show count",
    "FilterExpandedColumn": "Expanded",
    "FilterSortByColumn": "Sort by",
    "FilterSortByCount": "Count",
    "FilterSortByName": "Alphabetical",
    "FilterSortDirectionColumn": "Sort direction",
    "FilterSortDescending": "Descending",
    "FilterSortAscending": "Ascending",
    "FilterMultiValuesColumn": "Multi-select",
    "FilterDependsOnColumn": "Depends on",
    "FilterShowWhenParentHasValueColumn": "Show only after parent selection",
    "FilterHideZeroCountValuesColumn": "Hide zero-count values",
    "FilterResetWhenParentChangesColumn": "Reset when parent changes",
    "FilterTrueLabelColumn": "True label",
    "FilterFalseLabelColumn": "False label",
    "FilterInvertBooleanColumn": "Invert boolean semantics",
    "FilterAudienceColumn": "Audience (Entra group IDs)",
    "FilterAudiencePlaceholder": "Entra group object IDs only; no users or SharePoint groups",
    "ApplyModeLabel": "Apply mode",
    "ApplyModeInstant": "Instant (apply on each selection)",
    "ApplyModeManual": "Manual (apply with button)",
    "OperatorLabel": "Logic between refiners",
    "ShowClearAllLabel": "Show Clear All button",
    "ClearAllFiltersLabel": "Clear all",
    "ShowFiltersLabel": "Show filters",
    "FiltersPanelHeaderLabel": "Filters",
    "CloseFiltersLabel": "Close filters",
    "EnableVisualFilterBuilderLabel": "Enable visual filter builder",
    "ToggleOnText": "Yes",
    "ToggleOffText": "No",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "AudienceTargetingGroupName": "Audience targeting",
    "AudienceTargetingLabel": "Visible to (Entra group object IDs)",
    "AudienceTargetingDescription": "Comma- or newline-separated Microsoft Entra group object IDs. Current support is group and directory-role IDs returned by Microsoft Graph /me/memberOf only. User emails, UPNs, SharePoint group names, and nested group-only membership do not match. Leave blank to show this web part to everyone. Requires the User.Read Graph permission to be approved at SharePoint admin → API access."
  }
});
