declare interface ISpSearchFiltersWebPartStrings {
  PropertyPaneDescription: string;
  FiltersPageHeader: string;
  ConnectionsPageHeader: string;
  AdvancedPageHeader: string;
  FiltersGroupName: string;
  BehaviorGroupName: string;
  ConnectionsGroupName: string;
  AdvancedGroupName: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  SearchContextIdLabel: string;
  SearchContextIdDescription: string;
  FiltersFieldLabel: string;
  FiltersPanelHeader: string;
  FiltersManageBtn: string;
  FilterPropertyColumn: string;
  FilterDisplayNameColumn: string;
  FilterUrlAliasColumn: string;
  FilterTypeColumn: string;
  FilterTypeCheckbox: string;
  FilterTypeDateRange: string;
  FilterTypeText: string;
  FilterTypeSlider: string;
  FilterTypePeople: string;
  FilterTypeTaxonomy: string;
  FilterTypeTagBox: string;
  FilterTypeToggle: string;
  FilterOperatorColumn: string;
  FilterMaxValuesColumn: string;
  FilterShowCountColumn: string;
  FilterExpandedColumn: string;
  FilterSortByColumn: string;
  FilterSortByCount: string;
  FilterSortByName: string;
  FilterSortDirectionColumn: string;
  FilterSortDescending: string;
  FilterSortAscending: string;
  FilterMultiValuesColumn: string;
  ApplyModeLabel: string;
  ApplyModeInstant: string;
  ApplyModeManual: string;
  OperatorLabel: string;
  ShowClearAllLabel: string;
  EnableVisualFilterBuilderLabel: string;
  ToggleOnText: string;
  ToggleOffText: string;
  AppLocalEnvironmentSharePoint: string;
  AppLocalEnvironmentTeams: string;
  AppLocalEnvironmentOffice: string;
  AppLocalEnvironmentOutlook: string;
  AppSharePointEnvironment: string;
  AppTeamsTabEnvironment: string;
  AppOfficeEnvironment: string;
  AppOutlookEnvironment: string;
  UnknownEnvironment: string;
}

declare module 'SpSearchFiltersWebPartStrings' {
  const strings: ISpSearchFiltersWebPartStrings;
  export = strings;
}
