declare interface ISpSearchFiltersWebPartStrings {
  PropertyPaneDescription: string;
  FiltersPageHeader: string;
  ConnectionsPageHeader: string;
  AdvancedPageHeader: string;
  FiltersGroupName: string;
  BehaviorGroupName: string;
  ConnectionsGroupName: string;
  AdvancedGroupName: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  SearchContextIdLabel: string;
  SearchContextIdDescription: string;
  FiltersFieldLabel: string;
  FiltersPanelHeader: string;
  FiltersManageBtn: string;
  FilterPropertyColumn: string;
  FilterDisplayNameColumn: string;
  FilterUrlAliasColumn: string;
  FilterTypeColumn: string;
  FilterTypeCheckbox: string;
  FilterTypeDropdown: string;
  FilterTypeDateRange: string;
  FilterTypeText: string;
  FilterTypeSlider: string;
  FilterTypePeople: string;
  FilterTypeTaxonomy: string;
  FilterTypeTagBox: string;
  FilterTypeToggle: string;
  FilterOperatorColumn: string;
  FilterMaxValuesColumn: string;
  FilterShowCountColumn: string;
  FilterExpandedColumn: string;
  FilterSortByColumn: string;
  FilterSortByCount: string;
  FilterSortByName: string;
  FilterSortDirectionColumn: string;
  FilterSortDescending: string;
  FilterSortAscending: string;
  FilterMultiValuesColumn: string;
  FilterDependsOnColumn: string;
  FilterShowWhenParentHasValueColumn: string;
  FilterHideZeroCountValuesColumn: string;
  FilterResetWhenParentChangesColumn: string;
  FilterTrueLabelColumn: string;
  FilterFalseLabelColumn: string;
  FilterInvertBooleanColumn: string;
  FilterAudienceColumn: string;
  FilterAudiencePlaceholder: string;
  ApplyModeLabel: string;
  ApplyModeInstant: string;
  ApplyModeManual: string;
  OperatorLabel: string;
  ShowClearAllLabel: string;
  ClearAllFiltersLabel: string;
  // T1.D1 — phone-width drawer (≤639px). `ShowFiltersLabel` is the toggle
  // affordance; `FiltersPanelHeaderLabel` is the drawer's Panel header;
  // `CloseFiltersLabel` is the Panel's close-button aria-label.
  ShowFiltersLabel: string;
  FiltersPanelHeaderLabel: string;
  CloseFiltersLabel: string;
  EnableVisualFilterBuilderLabel: string;
  ToggleOnText: string;
  ToggleOffText: string;
  AppLocalEnvironmentSharePoint: string;
  AppLocalEnvironmentTeams: string;
  AppLocalEnvironmentOffice: string;
  AppLocalEnvironmentOutlook: string;
  AppSharePointEnvironment: string;
  AppTeamsTabEnvironment: string;
  AppOfficeEnvironment: string;
  AppOutlookEnvironment: string;
  UnknownEnvironment: string;
  AudienceTargetingGroupName: string;
  AudienceTargetingLabel: string;
  AudienceTargetingDescription: string;
}

declare module 'SpSearchFiltersWebPartStrings' {
  const strings: ISpSearchFiltersWebPartStrings;
  export = strings;
}
