define([], function() {
  return {
    "PropertyPaneDescription": "Configure the search results display, layout, and data source settings.",
    "DataGroupName": "Search Configuration",
    "QuerySettingsGroupName": "Query Settings",
    "PaginationGroupName": "Pagination",
    "LayoutGroupName": "Layout",
    "MainLayoutsGroupName": "Views",
    "AdvancedLayoutsGroupName": "Specialized Views",
    "SortGroupName": "Sort",
    "GeneralGroupName": "General",
    "BehaviorGroupName": "Behavior",
    "ConnectionsGroupName": "Connections",
    "AdvancedGroupName": "Advanced",
    "AboutGroupName": "About",
    "SearchContextIdLabel": "Search Context ID",
    "SearchContextIdDescription": "Identifier to connect this web part with other search web parts (search box, filters, verticals).",
    "SearchScopeLabel": "Search Scope",
    "ScopeAllText": "All SharePoint",
    "ScopeCurrentSiteText": "Current site only",
    "ScopeCurrentCollectionText": "Current site collection",
    "ScopeCustomText": "Custom path",
    "SearchScopePathLabel": "Custom scope path",
    "SearchScopePathDescription": "Full URL of the site or library to restrict results to.",
    "QueryTemplateLabel": "Query Template",
    "QueryTemplateDescription": "KQL query template. Use {searchTerms} as the placeholder for the user query.",
    "ResultSourceIdLabel": "Result Source ID",
    "ResultSourceIdDescription": "GUID of a SharePoint result source. Leave blank to use the default.",
    "SelectedPropertiesLabel": "Selected Properties",
    "SelectedPropertiesDescription": "Managed properties to retrieve. Order determines column display priority.",
    "SelectedPropertiesPanelHeader": "Configure selected managed properties",
    "SelectedPropertiesManageBtn": "Manage properties",
    "SelectedPropertyColumn": "Managed property",
    "SelectedPropertyAliasColumn": "Alias (display label)",
    "CompactViewGroupName": "Compact View",
    "CompactPropertiesLabel": "Compact View Fields",
    "CompactPropertiesDescription": "Metadata fields shown in Compact List next to the title.",
    "CompactPropertiesPanelHeader": "Configure compact view fields",
    "CompactPropertiesManageBtn": "Manage compact fields",
    "GridViewGroupName": "Data Grid",
    "GridPropertiesLabel": "Data Grid Columns",
    "GridPropertiesPanelHeader": "Configure data grid columns",
    "GridPropertiesManageBtn": "Manage data grid columns",
    "RefinementFiltersLabel": "Refinement Filters",
    "RefinementFiltersDescription": "Persistent filters applied to every query.",
    "RefinementFiltersPanelHeader": "Configure persistent refinement filters",
    "RefinementFiltersManageBtn": "Manage filters",
    "RefinementFilterPropertyColumn": "Managed property",
    "RefinementFilterOperatorColumn": "Operator",
    "RefinementFilterValueColumn": "Value",
    "FqlOperatorEquals": "Equals",
    "FqlOperatorContains": "Contains",
    "FqlOperatorRange": "Range",
    "FqlOperatorBeginsWith": "Begins with",
    "CollapseSpecificationLabel": "Collapse Specification",
    "CollapseSpecificationDescription": "Collapse duplicate results (e.g. \"Author:1 Site:2\").",
    "EnableQueryRulesLabel": "Enable query rules",
    "TrimDuplicatesLabel": "Trim duplicates",
    "PageSizeLabel": "Results per page",
    "ShowPagingLabel": "Show pagination",
    "PageRangeLabel": "Page range",
    "PageRangeDescription": "Number of page buttons to display in the pagination bar.",
    "DefaultLayoutLabel": "Starting View",
    "ScenarioPresetLabel": "Scenario Preset",
    "ScenarioPresetHint": "A preset configures layout, query template, and result columns. Filters and Verticals web parts are configured separately. Select Custom to configure everything manually.",
    "ListLayoutText": "List",
    "CompactLayoutText": "Compact List",
    "GridLayoutText": "Data Grid",
    "CardLayoutText": "Card",
    "PeopleLayoutText": "People",
    "GalleryLayoutText": "Gallery",
    "ShowResultCountLabel": "Show result count",
    "ShowSortDropdownLabel": "Show sort dropdown",
    "ShowDeleteConfirmationLabel": "Confirm before deleting grid items",
    "ShowPreviewPanelLabel": "Enable preview panel",
    "HideWebPartWhenNoResultsLabel": "Hide web part when no results",
    "TitleDisplayModeLabel": "Document title display",
    "TitleDisplayEllipsisText": "Cut off at end (...)",
    "TitleDisplayMiddleText": "Cut in middle",
    "TitleDisplayWrapText": "Wrap to multiple lines",
    "SortFieldLabel": "Sort fields",
    "SortPanelHeader": "Configure available sort options",
    "SortManageBtn": "Manage sort fields",
    "SortPropertyColumn": "Managed property",
    "SortLabelColumn": "Label",
    "SortDirectionColumn": "Direction",
    "SortAscending": "Ascending",
    "SortDescending": "Descending",
    "EnableSelectionLabel": "Enable result selection",
    "ToggleOnText": "On",
    "ToggleOffText": "Off",
    "DataSourcePageHeader": "Configure search data source and query settings.",
    "DisplayPageHeader": "Configure layout, sort, and display options.",
    "ConnectionsPageHeader": "Configure connections to other search web parts on the page.",
    "AdvancedPageHeader": "Configure expert search and grid behaviors.",
    "AboutPageHeader": "SP Search Results Web Part"
  }
});
