define([], function() {
  return {
    "PropertyPaneDescription": "Configure the search results display, layout, and data source settings.",
    "DataGroupName": "Data Source",
    "DisplayGroupName": "Display Settings",
    "SearchContextIdLabel": "Search Context ID",
    "SearchContextIdDescription": "Identifier to connect this web part with other search web parts (search box, filters, verticals).",
    "QueryTemplateLabel": "Query Template",
    "QueryTemplateDescription": "KQL query template. Use {searchTerms} as the placeholder for the user query.",
    "SelectedPropertiesLabel": "Selected Properties",
    "SelectedPropertiesDescription": "Comma-separated list of managed properties to retrieve from the search index.",
    "PageSizeLabel": "Results per page",
    "DefaultLayoutLabel": "Default Layout",
    "ListLayoutText": "List",
    "CompactLayoutText": "Compact",
    "ShowResultCountLabel": "Show result count",
    "ShowSortDropdownLabel": "Show sort dropdown",
    "SortFieldLabel": "Sort fields",
    "SortPanelHeader": "Configure available sort options",
    "SortManageBtn": "Manage sort fields",
    "SortPropertyColumn": "Managed property",
    "SortLabelColumn": "Label",
    "SortDirectionColumn": "Direction",
    "SortAscending": "Ascending",
    "SortDescending": "Descending",
    "EnableSelectionLabel": "Enable result selection",
    "ToggleOnText": "On",
    "ToggleOffText": "Off"
  }
});
