define([], function() {
  return {
    "PropertyPaneDescription": "Configure the search results display, layout, and data source settings.",
    "DataGroupName": "Search Configuration",
    "QuerySettingsGroupName": "Query Settings",
    "PaginationGroupName": "Pagination",
    "LayoutGroupName": "Layout",
    "MainLayoutsGroupName": "Views",
    "AdvancedLayoutsGroupName": "Specialized Views",
    "SortGroupName": "Sort",
    "GeneralGroupName": "General",
    "BehaviorGroupName": "Behavior",
    "ConnectionsGroupName": "Connections",
    "AdvancedGroupName": "Advanced",
    "AboutGroupName": "About",
    "SearchContextIdLabel": "Search Context ID",
    "SearchContextIdDescription": "Identifier to connect this web part with other search web parts (search box, filters, verticals).",
    "SearchScopeLabel": "Search Scope",
    "ScopeAllText": "All SharePoint",
    "ScopeCurrentSiteText": "Current site only",
    "ScopeCurrentCollectionText": "Current site collection",
    "ScopeCustomText": "Custom path",
    "SearchScopePathLabel": "Custom scope path",
    "SearchScopePathDescription": "Full URL of the site or library to restrict results to.",
    "QueryTemplateLabel": "Query Template",
    "QueryTemplateDescription": "KQL query template. Use {searchTerms} as the placeholder for the user query.",
    "ResultSourceIdLabel": "Result Source ID",
    "ResultSourceIdDescription": "GUID of a SharePoint result source. Leave blank to use the default.",
    "SelectedPropertiesLabel": "Selected Properties",
    "SelectedPropertiesDescription": "Managed properties to retrieve. Order determines column display priority.",
    "SelectedPropertiesPanelHeader": "Configure selected managed properties",
    "SelectedPropertiesManageBtn": "Manage properties",
    "SelectedPropertyColumn": "Managed property",
    "SelectedPropertyAliasColumn": "Alias (display label)",
    "CompactViewGroupName": "Compact View",
    "CompactPropertiesLabel": "Compact View Fields",
    "CompactPropertiesDescription": "Metadata fields shown in Compact List next to the title.",
    "CompactPropertiesPanelHeader": "Configure compact view fields",
    "CompactPropertiesManageBtn": "Manage compact fields",
    "GridViewGroupName": "Data Grid",
    "GridPropertiesLabel": "Data Grid Columns",
    "GridPropertiesPanelHeader": "Configure data grid columns",
    "GridPropertiesManageBtn": "Manage data grid columns",
    "RefinementFiltersLabel": "Refinement Filters",
    "RefinementFiltersDescription": "Persistent filters applied to every query.",
    "RefinementFiltersPanelHeader": "Configure persistent refinement filters",
    "RefinementFiltersManageBtn": "Manage filters",
    "RefinementFilterPropertyColumn": "Managed property",
    "RefinementFilterOperatorColumn": "Operator",
    "RefinementFilterValueColumn": "Value",
    "FqlOperatorEquals": "Equals",
    "FqlOperatorContains": "Contains",
    "FqlOperatorRange": "Range",
    "FqlOperatorBeginsWith": "Begins with",
    "CollapseSpecificationLabel": "Collapse Specification",
    "CollapseSpecificationDescription": "Collapse duplicate results (e.g. \"Author:1 Site:2\").",
    "EnableQueryRulesLabel": "Enable query rules",
    "TrimDuplicatesLabel": "Trim duplicates",
    "PageSizeLabel": "Results per page",
    "ShowPagingLabel": "Show pagination",
    "PageRangeLabel": "Page range",
    "PageRangeDescription": "Number of page buttons to display in the pagination bar.",
    "DefaultLayoutLabel": "Starting View",
    "ScenarioPresetLabel": "Scenario Preset",
    "ScenarioPresetHint": "A preset configures layout, query template, and result columns. Filters and Verticals web parts are configured separately. Select Custom to configure everything manually.",
    "ScenarioPresetPeopleWarning": "The People preset needs Microsoft Graph access. The preset is applied but the People results will be empty until a tenant admin approves the People.Read (and optionally User.Read.All / Sites.Read.All) Graph permissions at SharePoint admin centre → Advanced → API access.",
    "GetStartedGroupName": "Get started",
    "ListLayoutText": "List",
    "CompactLayoutText": "Compact List",
    "GridLayoutText": "Data Grid",
    "CardLayoutText": "Card",
    "PeopleLayoutText": "People",
    "GalleryLayoutText": "Gallery",
    "ShowResultCountLabel": "Show result count",
    "ShowSortDropdownLabel": "Show sort dropdown",
    "ShowDeleteConfirmationLabel": "Confirm before deleting grid items",
    "ShowPreviewPanelLabel": "Enable preview panel",
    "HideWebPartWhenNoResultsLabel": "Hide web part when no results",
    "TitleDisplayModeLabel": "Document title display",
    "TitleDisplayEllipsisText": "Cut off at end (...)",
    "TitleDisplayMiddleText": "Cut in middle",
    "TitleDisplayWrapText": "Wrap to multiple lines",
    "SortFieldLabel": "Sort fields",
    "SortPanelHeader": "Configure available sort options",
    "SortManageBtn": "Manage sort fields",
    "SortPropertyColumn": "Managed property",
    "SortLabelColumn": "Label",
    "SortDirectionColumn": "Direction",
    "SortAscending": "Ascending",
    "SortDescending": "Descending",
    "EnableSelectionLabel": "Enable result selection",
    "ToggleOnText": "On",
    "ToggleOffText": "Off",
    "DataSourcePageHeader": "Configure search data source and query settings.",
    "DisplayPageHeader": "Configure layout, sort, and display options.",
    "ConnectionsPageHeader": "Configure connections to other search web parts on the page.",
    "AdvancedPageHeader": "Configure expert search and grid behaviors.",
    "AboutPageHeader": "SP Search Results Web Part",
    "ResultLinkGroupName": "Result link behaviour",
    "ResultClickTargetLabel": "When a result is clicked",
    "ResultClickTargetPanelText": "Open the preview pop-up (default — today’s behaviour for files; new tab for other items)",
    "ResultClickTargetNewTabText": "Open in a new tab",
    "ResultClickTargetSameTabText": "Open in the same tab",
    "ResultClickTargetSidePanelText": "Open the detail side-panel",
    "DocumentLinkModeLabel": "For document results, the link opens",
    "DocumentLinkModeFileText": "The file",
    "DocumentLinkModePropertiesFormText": "Its properties form (DispForm)",
    "ListItemLinkModeLabel": "For list-item results, the link opens",
    "ListItemLinkModeDisplayFormText": "The display form (view)",
    "ListItemLinkModeEditFormText": "The edit form",
    "EmptyResultsMessageLabel": "Custom empty-results message (HTML)",
    "EmptyResultsMessageDescription": "HTML shown when a search returns no results. Leave blank to use the default contextual message. Script tags and event handlers are stripped before render.",
    "ShowColumnChooserLabel": "Show column chooser",
    "SelectedPropertiesAliasDeprecationNote": "Display labels (the alias column above) have moved to the Data Grid and Compact column editors. The alias value here is preserved for back-compat but no longer drives the column header.",
    "AudienceTargetingGroupName": "Audience targeting",
    "AudienceTargetingLabel": "Visible to (Entra group object IDs)",
    "AudienceTargetingDescription": "Comma- or newline-separated Microsoft Entra group object IDs. Current support is group and directory-role IDs returned by Microsoft Graph /me/memberOf only. User emails, UPNs, SharePoint group names, and nested group-only membership do not match. Leave blank to show this web part to everyone. Requires the User.Read Graph permission to be approved at SharePoint admin → API access."
  }
});
