define([], function() {
  return {
    "PropertyPaneDescription": "Configure search verticals to provide tab-based content scoping with badge counts and audience targeting.",
    "BasicGroupName": "Vertical Settings",
    "ConnectionGroupName": "Connection",
    "VerticalsGroupName": "Verticals",
    "DisplayGroupName": "Display",
    "VerticalsPageHeader": "Configure search verticals, link tabs, and audience targeting.",
    "DisplayPageHeader": "Configure vertical display and tab style.",
    "SearchContextIdFieldLabel": "Search Context ID",
    "SearchContextIdFieldDescription": "Unique identifier to connect this web part with other search web parts on the page.",
    "VerticalsFieldLabel": "Verticals",
    "VerticalsPanelHeader": "Configure search verticals",
    "VerticalsManageBtn": "Manage verticals",
    "VerticalsIntroLabel": "Each vertical is a tab that can narrow results or link to another page. Drag to reorder. You can configure query, provider, result source, layout override, audience, and link behavior here.",
    "VerticalKeyColumn": "Key",
    "VerticalLabelColumn": "Label",
    "VerticalIconColumn": "Icon",
    "VerticalQueryColumn": "Search query",
    "VerticalSourceColumn": "Result Source ID",
    "VerticalIsLinkColumn": "Is link",
    "VerticalLinkUrlColumn": "Link URL",
    "VerticalOpenBehaviorColumn": "Open behavior",
    "OpenBehaviorCurrentTab": "Current tab",
    "OpenBehaviorNewTab": "New tab",
    "VerticalProviderColumn": "Data provider",
    "VerticalDefaultLayoutColumn": "Default layout",
    "VerticalAudienceColumn": "Audience (Entra group IDs)",
    "VerticalAudiencePlaceholder": "Entra group object IDs only; no users or SharePoint groups",
    "DefaultVerticalLabel": "Default vertical",
    "ShowCountsFieldLabel": "Show result counts",
    "HideEmptyVerticalsFieldLabel": "Hide empty verticals",
    "TabStyleFieldLabel": "Tab style",
    "TabStyleTabs": "Tabs",
    "TabStylePills": "Pills",
    "TabStyleUnderline": "Underline",
    "ToggleOnText": "On",
    "ToggleOffText": "Off",
    "AudienceTargetingGroupName": "Audience targeting",
    "AudienceTargetingLabel": "Visible to (Entra group object IDs)",
    "AudienceTargetingDescription": "Comma- or newline-separated Microsoft Entra group object IDs. Current support is group and directory-role IDs returned by Microsoft Graph /me/memberOf only. User emails, UPNs, SharePoint group names, and nested group-only membership do not match. Leave blank to show this web part to everyone. Requires the User.Read Graph permission to be approved at SharePoint admin → API access. Note: this controls the whole tab strip; individual tab visibility uses the audience column in the Verticals collection editor."
  }
});
