define([], function() {
  return {
    "PropertyPaneDescription": "Configure search verticals to provide tab-based content scoping with badge counts and audience targeting.",
    "BasicGroupName": "Vertical Settings",
    "ConnectionGroupName": "Connection",
    "VerticalsGroupName": "Verticals",
    "DisplayGroupName": "Display",
    "VerticalsPageHeader": "Configure search verticals, link tabs, and audience targeting.",
    "DisplayPageHeader": "Configure vertical display and tab style.",
    "SearchContextIdFieldLabel": "Search Context ID",
    "SearchContextIdFieldDescription": "Unique identifier to connect this web part with other search web parts on the page.",
    "VerticalsFieldLabel": "Verticals",
    "VerticalsPanelHeader": "Configure search verticals",
    "VerticalsManageBtn": "Manage verticals",
    "VerticalsIntroLabel": "Each vertical is a tab that can narrow results or link to another page. Drag to reorder. You can configure query, provider, result source, layout override, audience, and link behavior here.",
    "VerticalKeyColumn": "Key",
    "VerticalLabelColumn": "Label",
    "VerticalIconColumn": "Icon",
    "VerticalQueryColumn": "Search query",
    "VerticalSourceColumn": "Result Source ID",
    "VerticalIsLinkColumn": "Is link",
    "VerticalLinkUrlColumn": "Link URL",
    "VerticalOpenBehaviorColumn": "Open behavior",
    "OpenBehaviorCurrentTab": "Current tab",
    "OpenBehaviorNewTab": "New tab",
    "VerticalProviderColumn": "Data provider",
    "VerticalDefaultLayoutColumn": "Default layout",
    "VerticalAudienceColumn": "Audience",
    "VerticalAudiencePlaceholder": "Entra ID group IDs (comma-separated)",
    "DefaultVerticalLabel": "Default vertical",
    "ShowCountsFieldLabel": "Show result counts",
    "HideEmptyVerticalsFieldLabel": "Hide empty verticals",
    "TabStyleFieldLabel": "Tab style",
    "TabStyleTabs": "Tabs",
    "TabStylePills": "Pills",
    "TabStyleUnderline": "Underline",
    "ToggleOnText": "On",
    "ToggleOffText": "Off"
  }
});
