define([], function() {
  return {
    "PropertyPaneDescription": "Configure the Admin Search Manager web part for search diagnostics, coverage monitoring, and search insights.",
    "ConnectionGroupName": "Connection",
    "DisplayGroupName": "Display",
    "SectionsGroupName": "Sections",
    "SearchContextIdLabel": "Search Context ID",
    "SearchContextIdDescription": "Optional. Use the same ID as any search web parts on this admin page only if you want replay actions to target that experience.",
    "CoverageSourcePageUrlLabel": "Search page URL",
    "CoverageSourcePageUrlDescription": "Optional. Point to the search page whose Search Results configuration should be used to auto-detect coverage scope. Leave blank to inspect the current page.",
    "DefaultTabLabel": "Default tab",
    "DefaultTabCoverage": "Coverage",
    "DefaultTabHealth": "Health",
    "DefaultTabInsights": "Insights",
    "EnableCoverageLabel": "Enable coverage tab",
    "EnableHealthLabel": "Enable health tab",
    "EnableInsightsLabel": "Enable insights tab",
    "MonitoringGroupName": "Monitoring",
    "CoverageProfilesLabel": "Coverage profiles",
    "CoverageProfilesPanelHeader": "Coverage monitoring profiles",
    "CoverageProfilesManageButton": "Manage coverage profiles",
    "CoverageProfileTitleColumn": "Title",
    "CoverageProfileDescriptionColumn": "Description",
    "CoverageProfileSourceUrlsColumn": "List or library URLs",
    "CoverageProfileContentTypesColumn": "Content type IDs",
    "CoverageProfileExcludePathsColumn": "Excluded paths",
    "CoverageProfileQueryTemplateColumn": "Query template",
    "CoverageProfileResultSourceColumn": "Result source ID",
    "CoverageProfileRefinementFiltersColumn": "Refinement filters",
    "CoverageProfileIncludeFoldersColumn": "Include folders",
    "CoverageProfileTrimDuplicatesColumn": "Trim duplicates",
    "AccessDeniedTitle": "Access denied",
    "AccessDeniedDescription": "Only site owners or users with Manage Web permission can use the Admin Search Manager.",
    "ToggleOnText": "On",
    "ToggleOffText": "Off"
  }
});
